### ISSUE TITLE
telegraf configuration fix

### ISSUE THREAD

**Issue by giudig** [ratibor78/srvstatus#2]
Very interesting script!
Unfortunately in my environment based on CentOS 7 telegraf service is not able to run directly the service.py command. I found this issue:

[root@myserver /]# su -c '/opt/srvstatus/service.py' -s /bin/bash telegraf
Traceback (most recent call last):
  File "/opt/srvstatus/service.py", line 12, in <module>
    import configparser
ImportError: No module named configparser

[root@myserver /]# su -c '/opt/srvstatus/venv/bin/python /opt/srvstatus/service.py' -s /bin/bash telegraf
[{"status": 1, "status_time": 868647, "service": "elasticsearch.service"}, {"status": 1, "status_time": ........... "sshd.service"}]

I solved using this this configuration for exec input:

    [[inputs.exec]]

    commands = [
     "/opt/srvstatus/venv/bin/python /opt/srvstatus/service.py"
    ]

    timeout = "5s"
    name_override = "services_stats"
    data_format = "json"
    tag_keys = [
      "service"
    ]

**Comment by ratibor78** [comment]
Hi, @giudig thanks for the information, yep it looks like the issue, It looks like system Python knows nothing about the installed packages in venv, I will check and fix the documentation to the full path for the python from virtual env. It looks like this package was installed in my system that's why. Thanks for your attention and time.

**Comment by ratibor78** [comment]
I guess we now can close this issue.
